/* symbols */
#pragma once

#define DE_USCORE        QMARK
#define DE_CIRCLE        TILDE
#define DE_LBRCKT        RA(N8)
#define DE_RBRCKT        RA(N9)
#define DE_LBRACE        RA(N7)
#define DE_RBRACE        RA(N0)
#define DE_LPAR          STAR
#define DE_RPAR          LPAR
#define DE_BSLASH        RA(MINUS)
#define DE_FSLASH        AMPERSAND
#define DE_CARET         GRAVE
#define DE_STAR          RIGHT_BRACE
#define DE_HASH          BACKSLASH
#define DE_DOLLAR        DOLLAR
#define DE_PIPE          RA(LESS_THAN)
#define DE_TILDE         RA(PLUS)
#define DE_GRAVE         PLUS
#define DE_EXCL          EXCLAMATION
#define DE_LT            BACKSLASH
#define DE_GT            PIPE
#define DE_EQ            KP_EQUAL
#define DE_AMP           SLASH
#define DE_PARA          HASH
#define DE_QMARK         UNDERSCORE
#define DE_MINUS         KP_MINUS
#define DE_COLON         GREATER_THAN
#define DE_AT            RA(Q)
#define DE_PLUS          KP_PLUS
#define DE_PERCENT       PERCENT
#define DE_DQT           AT_SIGN
#define DE_SQT           PIPE2
#define DE_SCOLON        LESS_THAN
#define DE_EURO          RA(E)
#define DE_GRAVE         PLUS
